custom_css = {
    'header': {
        'color': 'white',
        'background-color': '#007bff',
        'padding': '10px',
        'border-radius': '5px',
    },
    'button': {
        'background-color': '#007bff',
        'color': 'white',
        'border': 'none',
        'border-radius': '5px',
        'padding': '10px 20px',
        'margin': '5px',
        'font-size': '12px',
    },
    'input': {
        'margin': '10px',
        'padding': '5px',
        'border-radius': '5px',
        'border': '1px solid #007bff',
        'flex-grow': '1',
    },
    'dropdown': {
        'margin': '10px',
        'padding': '5px',
        'border-radius': '5px',
        'border': '1px solid #007bff',
        'font-size': '12px',
    },
    'upload': {
        'width': '100%',
        'height': '120px',
        'lineHeight': '120px',
        'borderWidth': '1px',
        'borderStyle': 'dashed',
        'borderRadius': '5px',
        'textAlign': 'center',
        'margin': '10px',
        'border-color': '#007bff',
    },
    'toggle-button': {
        'background-color': '#007bff',
        'color': 'white',
        'border': 'none',
        'border-radius': '5px',
        'padding': '5px 10px',
        'width': '100%',
    },
    'axis-selection': {
        'padding': '10px',
        'border': '1px solid #007bff',
        'border-radius': '5px',
        'margin': '10px',
        'font-size': '12px',
    },
    'tabs': {
        'margin': '10px',
    },
    'graph': {
        'background-color': '#f8f9fa',
        'padding': '10px',
        'border': '1px solid #007bff',
        'border-radius': '5px',
    },
    'small-text': {
        'font-size': '12px',
        'overflowX': 'auto',
        'max-width': '100%',
    },
}
